### ISSUE TITLE
environment file needs to be updated 

### ISSUE THREAD

**Issue by stowerslab** [dattalab/keypoint-moseq#12]
while installing keypoint-moseq from the environment file provided (environment.win64_gpu.yml),  we ran into this error

The conflict is caused by:
    The user requested jax-moseq==0.0.0
    keypoint-moseq 0.0.1 depends on jax-moseq==0.0.1

changing the version to "jax-moseq==0.0.1" under pip solves it.

not sure if the other environment files for other OS should also be updated

**Comment by calebweinreb** [comment]
Thanks! Fixed in https://github.com/dattalab/keypoint-moseq/commit/1dd88b0a3f59fe17a45ba7efc189959ef776a00c
