### ISSUE TITLE
`visualize_transition_bigram` fails by default if `label_syllables` hasn't been run

### ISSUE THREAD

**Issue by jonahpearl** [dattalab/keypoint-moseq#127]
Problem:
`visualize_transition_bigram()` has `show_syllable_name=True` by default, which means it tries to load them from a csv with `get_syllable_names()`. 

That function then has:
```python
if os.path.exists(syll_info_path):
    syll_info_df = pd.read_csv(syll_info_path, index_col=False).fillna("")
```
but then no `else` block. So if `syll_info_df` doesn't exist, it raises `UnboundLocalError: local variable 'syll_info_df' referenced before assignment` a few lines later.

Proposed solution: 
`get_syllable_names()` should raise a human-understandable error if the csv with names doesn't exist yet. Alternatively, could check if the csv file exists in `visualize_transition_bigram()` and if it doesn't, just default to indices.

**Comment by jonahpearl** [comment]
(I also see now that you can just get the raw tm's from `generate_transition_matrices`, which is all I wanted, but the above issue still stands.)

**Comment by versey-sherry** [comment]
9361a74ba119f22c4db9ebb40e410d09e276f0d3

**Comment by calebweinreb** [comment]
@versey-sherry is this resolved? If so feel free to close. Thanks!
