### ISSUE TITLE
ValueError in loading keypoints from maDeepLabCut dataset

### ISSUE THREAD

**Issue by mshallow** [dattalab/keypoint-moseq#128]
When trying to use load_keypoints to load data from a maDLC dataset, it throws an error somewhere in the check_nan_proportions step of this function.

coordinates, confidences, bodyparts = kpms.load_keypoints(keypoint_data_path, 'deeplabcut', extension='h5')
# format data for modeling
data, metadata = kpms.format_data(coordinates, confidences, **config())

After these lines are run, the notebook displays that it has completed loading the keypoints, but it does not actually finish running the cell;

Loading keypoints: 100%|██████████████████| 1/1 [00:00<00:00, 12.31it/s]

this message is immediately followed by the following error:

ValueError                                Traceback (most recent call last)
Cell In[21], line 3
      1 # load data (e.g. from DeepLabCut)
      2 keypoint_data_path = '/Users/mollyshallow/Desktop/demo_project/' # can be a file, a directory, or a list of files
----> 3 coordinates, confidences, bodyparts = kpms.load_keypoints(keypoint_data_path, 'deeplabcut', extension='h5')
      5 # format data for modeling
      6 data, metadata = kpms.format_data(coordinates, confidences, **config())

File ~/opt/anaconda3/envs/keypoint_moseq/lib/python3.10/site-packages/keypoint_moseq/io.py:974, in load_keypoints(filepath_pattern, format, extension, recursive, path_sep, path_in_name, remove_extension)
    968     confidences.update(new_confidences)
    970 assert len(coordinates) > 0, fill(
    971     f"No valid results found for {filepath_pattern}"
    972 )
--> 974 check_nan_proportions(coordinates, bodyparts)
    975 return coordinates, confidences, bodyparts

File ~/opt/anaconda3/envs/keypoint_moseq/lib/python3.10/site-packages/keypoint_moseq/util.py:872, in check_nan_proportions(coordinates, bodyparts, warning_threshold, breakdown, **kwargs)
    870     _print_colored_table(keys, bodyparts, nan_props)
    871 else:
--> 872     all_coords = np.concatenate(list(coordinates.values()))
    873     nan_props = np.isnan(all_coords).any(-1).mean(0)
    874     if np.any(nan_props > warning_threshold):

File <__array_function__ internals>:180, in concatenate(*args, **kwargs)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 6 and the array at index 1 has size 2

I have tried using both a .csv and .h5 file as the DLC input and both of them generate the same error. I do have points tracked in my DLC dataset that are missing for a portion of the dataset so the file does contain a large number of nans for some of the bodyparts, but even on a file that does not contain these body parts, I encounter an error right around the same point of the code, but it is a slightly different error.

Is there something I am missing to make this step work? I tried to run the notebook on the example dataset, but the folders that should have contained the DLC tracking to use as keypoints were empty, so I have been testing it with one of my files.

**Comment by calebweinreb** [comment]
Hello,

Is this for social or single animal tracking? Probably the easiest way to debug this would be for you to send over an example file (calebsw@gmail.com). Also thanks for the heads up about the example data - I'll upload it in a more permanent place.

**Comment by mshallow** [comment]
This is for single animal tracking, but I use a multi-animal model because it has proven the cleanest way to track a mouse and cricket simultaneously.

**Comment by mshallow** [comment]
I'm also happy to work with the example data to set this up if that is an easier way to start!

**Comment by calebweinreb** [comment]
Is the cricket included in the file that you are submitting to keypoint moseq?

**Comment by mshallow** [comment]
I initially included it, which is what the file looked like when it generated this error, but then when I excluded the cricket, I got an error that said that local variables were referenced before assignment. 

This was the error:

Loading keypoints:   0%|                          | 0/1 [00:00<?, ?it/s]
Error loading /Users/mollyshallow/Desktop/demo_project/Sky_mouse-
1429_2023-01-
29T12_54_54DLC_dlcrnetms5_optopreycapFeb16shuffle1_150000_el_filtered.
csv: cannot reshape array of size 9642 into shape (9642,newaxis,3)
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
Cell In[22], line 3
      1 # load data (e.g. from DeepLabCut)
      2 keypoint_data_path = '/Users/mollyshallow/Desktop/demo_project/' # can be a file, a directory, or a list of files
----> 3 coordinates, confidences, bodyparts = kpms.load_keypoints(keypoint_data_path, 'deeplabcut', extension='csv')
      5 # format data for modeling
      6 data, metadata = kpms.format_data(coordinates, confidences, **config())

File ~/opt/anaconda3/envs/keypoint_moseq/lib/python3.10/site-packages/keypoint_moseq/io.py:967, in load_keypoints(filepath_pattern, format, extension, recursive, path_sep, path_in_name, remove_extension)
    964     except Exception as e:
    965         print(fill(f"Error loading {filepath}: {e}"))
--> 967     coordinates.update(new_coordinates)
    968     confidences.update(new_confidences)
    970 assert len(coordinates) > 0, fill(
    971     f"No valid results found for {filepath_pattern}"
    972 )

UnboundLocalError: local variable 'new_coordinates' referenced before assignment

**Comment by mshallow** [comment]
Ideally I would be able to use the file that contains the cricket points, but also can run preprocessing steps to remove those points.

**Comment by mshallow** [comment]
I just manually removed the cricket keypoints and columns from the document since I was just curious on a quick check if it was an issue with including the cricket points when loading the file. The DLC file was generated from a prey capture experiment, and we used multi-animal DLC instead of single animal because we wanted to track both the mouse and the cricket and doing this with single animal was throwing a lot of dropped points. To train the model I used the mouse as one of the individuals, and then the cricket was an "object" which is what allowed me to have different keypoints for both individuals. For what I am trying to use keypoint-moseq for, I don't need the cricket points.

**Comment by calebweinreb** [comment]
When you say the cricket was an object, does that mean you defined its keypoints under "Uniquebodyparts"? Or some other way?

**Comment by mshallow** [comment]
Yes, similar to how this is example for maDLC is set up, my mouse was the individual and then the cricket was the unique body parts. 
individuals:
-mouse

uniquebodyparts:
- anteriorC
- posteriorC

multianimalbodyparts:
- nose
- Lear
- Rear
- spine
- headbase
- tailbase

I am happy to send you the config file that was used for this model if that would be helpful!

**Comment by calebweinreb** [comment]
Sure! That would be great. Thanks! We'll add a feature to handle this scenario and then ping this thread when its available. Hopefully won't be more than a few days.

**Comment by mshallow** [comment]
Thank you! I'll send the dlc config your way.

**Comment by calebweinreb** [comment]
It should work now if you update to version 0.4.4
