### ISSUE TITLE
Linux GPU install error

### ISSUE THREAD

**Issue by bainro** [dattalab/keypoint-moseq#129]
I've had trouble installing on my linux machine for a while. I just settled for the CPU only env, but it was slow and would always fail at some point in training too. I'm trying to speed things up with the GPU again, but I am stuck at the following error from jax:

![image](https://github.com/dattalab/keypoint-moseq/assets/31903812/4cf1eb1b-cab3-4b31-b970-bbe775bb2986)

You can see my cuda toolkit version and drivers in that image. I am not sure if that's the one found through my anaconda env though, but I made no modifications to the conda yaml file. The only things I did was change etils to version 1.5.2

**Comment by bainro** [comment]
![image](https://github.com/dattalab/keypoint-moseq/assets/31903812/da1b9c40-3e22-4616-8180-8c7bacafa11a)
I'll try installing another cuda-nvcc

**Comment by bainro** [comment]
conda-forge dropped nvcc 11.* packages, but they're still available thru the nvidia channel:

![image](https://github.com/dattalab/keypoint-moseq/assets/31903812/e1ab8a51-bc81-418a-8675-e9f8ceb8c9cd)
![image](https://github.com/dattalab/keypoint-moseq/assets/31903812/7e20e2c0-6f7b-4e5e-bff0-32a9eaecb7a4)

Installing cuda-nvcc == 11.8.89 through the nvidia channel upgraded jax to 0.3.25, but it seems to be working now :) need to debug just a little more to ensure before closing ticket/issue.

**Comment by bainro** [comment]
Training is working :+1:

**Comment by calebweinreb** [comment]
Thanks for reporting this and all the detailed notes! Just updated the env file to incorporate your suggestions 
https://github.com/dattalab/keypoint-moseq/commit/a3c569381dc1ce8040dce1afd6ac7ddc945ce187
