### ISSUE TITLE
Sleap io requires python 3.9 but KPMS requires 3.8

### ISSUE THREAD

**Issue by jonahpearl** [dattalab/keypoint-moseq#138]
I made a python 3.8 conda env for KPMS and installed everything. Pip didn't preemptively complain for some reason, but when I tried `import keypoint_moseq` it failed because `sleap_io` requires python 3.9 (for typing). I have my own fork and made a hotfix so no rush, but I guess the options are to make sleap_io optional or upgrade to py 3.9!

Thanks!

**Comment by calebweinreb** [comment]
Done 
https://github.com/dattalab/keypoint-moseq/commit/9b30f8532265f320b397aa795bfa448e94ee2c64
