### ISSUE TITLE
Applying to videos from different setups

### ISSUE THREAD

**Issue by giacomovec** [dattalab/keypoint-moseq#148]
Hello, I have many videos with tracked points. My problem is that every video is from a different setup, so the rotation and scale of the keypoints doesn't match. How would I use your package with videos taken from different setups and cameras?

**Comment by calebweinreb** [comment]
Hi,

For differences in scale, you would need to resize the keypoints to a common scale before modeling them.

Can you elaborate on what you mean by the rotation not matching?

**Comment by giacomovec** [comment]
I think the rotation is already handled by your code.
For the difference in scale, I read that you were planning to implement a step to normalize them. Would that work? Do you know when will that be ready?
Thank you very much for your answer

**Comment by calebweinreb** [comment]
The method we are implementing is designed for more complicated normalization like differences in body shape. In your case, uniform scaling should work. You could use average statistics like nose-tail distance to determine the scale of each video and then uniformly scale the keypoints so they all share a common scale.
