### ISSUE TITLE
Problems importing Keypoint-MoSeq on Jupyter Notebook

### ISSUE THREAD

**Issue by JorgeVindelAlfageme** [dattalab/keypoint-moseq#150]
Hi! I'm new using Keypoint-MoSeq. I'm trying to execute it on my computer, but I haven't been able to. I followed the installation steps as they are indicated on: https://keypoint-moseq.readthedocs.io/en/latest/install.html. After using the command: "conda activate keypoint_moseq" and "jupyter notebook", I tried to import Keypoint-MoSeq, and the next error message appeared:

"XlaRuntimeError: UNKNOWN: no kernel image is available for execution on the device in external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_asm_compiler.cc(64): 'status'".

I guess that, based on what appears on: https://keypoint-moseq.readthedocs.io/en/latest/install.html, it has to do with the GPU version that I'm using. I tried to install CUDA using: "conda install cuda -c nvidia", but the problem wasn't solved. I'm not used to use my GPU, so I don't know how to solve it. Do you guys know what I should do? Thank you.

P. D.: The "nvidia-smi" output from Windows Powershell can be found on the next image:

![nvidia-smi_jorge](https://github.com/dattalab/keypoint-moseq/assets/70814540/017028da-63ea-4ace-8cb1-980482c71802)

**Comment by JorgeVindelAlfageme** [comment]
Here's how the error message looks like:

![XlaRuntimeError_cudaasmcompilercc64](https://github.com/dattalab/keypoint-moseq/assets/70814540/c4db4d30-cec0-4699-9566-a50e0af8353b)

**Comment by calebweinreb** [comment]
Which installation method did you use? conda or pip?

**Comment by JorgeVindelAlfageme** [comment]
I chose "Install using conda" path. I'm using a 64-bit Windows. I created a second environment using the "pip" method and a CPU-based approach and now I'm able to import Keypoint-MoSeq in Jupyter Notebook, but I would like to know more about how to use my GPU and those systems that depend on a related installation process. Here are my computer details if you want to check them directly. Thank you for your time:
![equipoJorge](https://github.com/dattalab/keypoint-moseq/assets/70814540/977b4d90-6c48-495f-92ea-cae11ca6f170)

**Comment by calebweinreb** [comment]
Did you see this note on the installation page and try following it? 

<img width="660" alt="Screenshot 2024-05-14 at 11 23 22 AM" src="https://github.com/dattalab/keypoint-moseq/assets/6147762/a5b7532d-aaa4-4eb9-b053-f61db3889cbf">

**Comment by calebweinreb** [comment]
Based on your GPU model and operating system, it looks like a newer driver is available: https://www.nvidia.com/download/driverResults.aspx/224483/en-us/

**Comment by JorgeVindelAlfageme** [comment]
Thank you for your answer. For now, I'm using the CPU-based version of Keypoint-MoSeq, but I want to check if I can solve this inconvenience with GPU. I'll try to download this new driver you recommended me and I'll write about the results in the next days.
