### ISSUE TITLE
stats_df in statistical analysis

### ISSUE THREAD

**Issue by cgeorgelou** [dattalab/keypoint-moseq#151]
Hi! I am using the notebook of the statistical analysis and I confront an issue on stats_df.
Actually, I want to compare the syllables among different states of one session (e.g. "punish" states vs "reward" states). For doing so, I made my own moseq_df, based on the one shown in the notebook, but I replaced the "group" column with "punish" and "reward" based on my frames (example attached).  
 
<img width="871" alt="Screenshot 2024-05-16 at 17 32 44" src="https://github.com/dattalab/keypoint-moseq/assets/139980642/d7a83353-8883-454f-802f-c91fd6ac0f8e">

So, I run:
```
import keypoint_moseq as kpms
project_dir='path/to/project' 
model_name='model_name' 
```
```
import pandas as pd
moseq_df= pd.read_csv('path/to/moseq_df **that I created**' ) 
```
```
stats_df = kpms.compute_stats_df(
    project_dir,
    model_name,
    moseq_df, 
    min_frequency=0.005,       
    groupby=['group', 'name'],        
    fps=30)                    

stats_df
```
Although no error appears, stats_df is an empty df and I wonder why since I specify project_dir, model_name and moseq_df above. Are there any limitations in the groups? Should they be different videos and not parts within the same video as I did?

**Comment by versey-sherry** [comment]
Hi, if you'd like to run stats_df, you'd need to have different groups for different videos since groups are intended for recording the experimental groups. Alternatively, you could label the syllables push/reward since that would be the behavior within a video, or you could use groupby in pandas to achieve dataframe analysis similar to stats_df.

**Comment by cgeorgelou** [comment]
Is it because the frames need to be consecutive for each group (so 1 video)?

**Comment by versey-sherry** [comment]
No, it is because the stats_df computes the syllable usage frequency by session (all syllable usages in one session add up to 1), and group is a key associated with the entire video in the package, so you can't have multiple group names in the same video.

**Comment by cgeorgelou** [comment]
Ok, I see, thank you!
