### ISSUE TITLE
Using keypoint-moseq for keypoint post processing

### ISSUE THREAD

**Issue by adrianloy** [dattalab/keypoint-moseq#154]
Hello, great project! In your paper you describe that the fitted model can be used for error correction of keypoint estimations. Is there an API in the code base to do that easily? What are your thoughts on doing this as a in-between step for a classification model that is trained in a supervised manner on keypoint estimation data? Since you mentioned that traditional signal smoothing techniques tend to delete information, this seems like a good idea to me to reduce the keypoint jitter in a more informed way.

**Comment by calebweinreb** [comment]
Hi,

This link explains how to export the estimated keypoint coordinates
https://keypoint-moseq.readthedocs.io/en/latest/advanced.html#exporting-pose-estimates

I would definitely inspect them manually before using them, however. In our test dataset, they seemed reasonable but I'm aware of other users who have gotten inaccurate estimates this way.
