### ISSUE TITLE
Question: what if not all behaviors are present in all videos? 

### ISSUE THREAD

**Issue by SusanL82** [dattalab/keypoint-moseq#159]
Hello, 

I'm looking forward to trying out keypoint-moseq on some of my behavioral data (exploration in an object recognition task, and in some open field settings). I have tracked my rats using a top-view DLC models that has no paws, but that does have shoulders and hips instead. 

I have previously tried to use VAME, but ran into trouble with my analyses when not all behavioral clusters were present in a given video. E.g. some rats rear and explore the arena walls a lot and others do not, or just don't do it in one of the video sessions. 
Is this a problem for keypoint-moseq? 

Or could I just prevent issues by making sure that there are some examples of everything in the training dataset? 

Best, 
Susan

**Comment by calebweinreb** [comment]
Hi,

Can you elaborate on why that was a problem with VAME? 

The way keypoint-moseq works is to essentially concatenate the data from all your recordings and then model them simultaneously. So if a behavior is not present in a given video, then the corresponding syllable won't appear in the output for that video.
