### ISSUE TITLE
Help Needed: Data Loader for 3D Posture Data from DANNCE

### ISSUE THREAD

**Issue by v738301** [dattalab/keypoint-moseq#160]
It is possible for you to help me write a data loader for my dataset? The dataset was generated using an open-source 3D tracking software called DANNCE (https://github.com/spoonsso/dannce).

This software generates 3D posture predictions in the following format:

	•	pred, data, and p_max are arrays with the shape [number of frames, dimension, number of keypoints].
	•	sampleID is the frame ID. [1, number of frames]
	•	metadata contains details about the prediction model.
	•	There are no keypoint labels inside this file; I usually label them manually during the analysis process.

Thank you in advance for your help!

![Capture](https://github.com/user-attachments/assets/416440be-a45a-470a-a84b-7b9e5d970631)
[save_data_AVG0.zip](https://github.com/user-attachments/files/16657200/save_data_AVG0.zip)

**Comment by calebweinreb** [comment]
Sure. What's in `pred` and `data`? Which one do you want to load as the final coordinates?

**Comment by v738301** [comment]
Thank you very much! I would like to load pred as the final coordinates. Pred contains the XYZ coordinates of all labels in every frame of the recorded video. Additionally, data is a matrix of the same size as pred and contains only zeros.
You can also experiment with the dataset I attached in my previous comment (save_data_AVG0.zip).

![Screenshot 2024-08-20 110538](https://github.com/user-attachments/assets/ecdc6c38-18de-432c-8b1a-ea50b4e7bce4)
![Screenshot 2024-08-20 110549](https://github.com/user-attachments/assets/a09ce906-230a-4ccf-9271-963ee9da2f6b)

**Comment by calebweinreb** [comment]
Sorry for the delay in getting to this. One more question: is there some type of standard config file in DANNCE that contains the names of the keypoints and a skeleton? If so, can you send an example?

**Comment by v738301** [comment]
Yes, DANNCE provides a .mat file that contains the names for all the labels and skeletons. In the rat18.mat file, it specifies the color, name of each label, and the connections between them.

<img width="944" alt="截圖 2024-08-27 17 14 24" src="https://github.com/user-attachments/assets/e37297e6-b5c6-40df-8146-f6f504f9e4a4">
<img width="943" alt="截圖 2024-08-27 17 14 33" src="https://github.com/user-attachments/assets/4bd9018c-2b27-475a-91dc-96c0b8ecffab">
<img width="945" alt="截圖 2024-08-27 17 14 40" src="https://github.com/user-attachments/assets/30592e7e-2438-49c9-92c7-edc1b6c0475b">

[rat18.mat.zip](https://github.com/user-attachments/files/16758822/rat18.mat.zip)

**Comment by calebweinreb** [comment]
I just pushed a new version (0.4.8) that includes DANNCE support. Names of bodyparts and the skeleton can be imported from a DANNCE config file using
```
kpms.setup_project(project_dir, dannce_config=...)
```
and keypoint predictions can be loaded using
```
kpms.load_keypoints(..., "dannce")
```
