### ISSUE TITLE
View keypoint video + ethogram/syllables interactively?

### ISSUE THREAD

**Issue by tuanpham96** [dattalab/keypoint-moseq#179]
Hi, I've been trying this out and this is so awesome! I was wondering if there's something already built in to interactively view the syllable series (like an ethogram) overlay under the corresponding videos. If not, do you have suggestions for an open source solution to do this?

**Comment by calebweinreb** [comment]
There isn't a way to do that directly in kpms but we did build another tool for that type of thing: https://github.com/calebweinreb/SNUB

**Comment by tuanpham96** [comment]
that looks super cool. thanks for the rec!
