### ISSUE TITLE
installation error missing future

### ISSUE THREAD

**Issue by laurelrr** [dattalab/keypoint-moseq#18]
I got the following error following your pip installation procedure: 
_ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
autograd 1.4 requires future>=0.15.2, which is not installed._

`pip install future>=0.15.2`  allowed me to import keypoint_moseq without the kernel image issue reported in readthedocs.
I think you might need to update the dependency list to include this package?

**Comment by calebweinreb** [comment]
Closing because this issue seems not to have come up for other any users.
