### ISSUE TITLE
Unable to fit the full model

### ISSUE THREAD

**Issue by kei-oga** [dattalab/keypoint-moseq#182]
Hi everyone, thank you for developing Keypoint Moseq(kpms); it is a really valuable tool. I've started using it, but I've encountered an issue. I am utilizing kpms on Google Colab Pro, and although I switched to Colab Pro for more memory, I was still unable to fit the full model due to running out of memory. Other works fine.

XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 16381782600 bytes. 

Here is my data set:
I have 198 CSV files, each recorded at 30 frames per second and lasting 4 minutes. This totals approximately 13 hours (198 files * 4 minutes / 60 minutes). 
Is this issue due to the length of the data set or some other factors?
I really appreciate your comments. Thank you.

**Comment by calebweinreb** [comment]
I am going to close this issue and we can continue to discuss over slack. Here is my slack response in case others see this issue:

Have you tried the suggestions here? https://keypoint-moseq.readthedocs.io/en/latest/FAQs.html#out-of-memory
13 hours is not too much but you'll need to apply one of the workarounds in the FAQ
