### ISSUE TITLE
Model specifications for benchmarking dataset

### ISSUE THREAD

**Issue by NeuTTH** [dattalab/keypoint-moseq#21]
Thanks for the great work! I am hoping to replicate some of the results in the paper with regards to the benchmarking datasets. It is mentioned in the applying keypoint-MoSeq section of the paper that:

> The one exception was $\kappa$ which we adjusted separately for each dataset to ensure a median state duration of 400ms.

I am wondering if $\kappa$ is different while training on the benchmarking datasets showed in Fig. 6. 
Thank you very much!

**Comment by calebweinreb** [comment]
Here is a table of parameters we used for each dataset. Let me know if you need any other information!

| Dataset | Latent dim | AR only | Full model |
|---------|-----------|---------|------------|
| Overhead 2D open field | 4 | 1e6 | 7e4 |
| Below-floor 2D open field | 6 | 1e6 | 1e3 |
| 3D open field | 6 | 1e6 | 2e4 |
| IMU dataset | 4 | 2.5e6 | 8e4 |
| Dopamine photometry | 4 | 2e6 | 3e5 |
| Rat7M | 8 | 1e9 | 7e4 |
| CalMS21 | 6 | 1e6 | 3.30e4 |
| DeepEthogram | 10 | 1e9 | 2e6 |
