### ISSUE TITLE
TypeError: The keyword `fps` is no longer supported. Use `duration`(in ms) instead, e.g. `fps=50` == `duration=20` (1000 * 1/50).

### ISSUE THREAD

**Issue by juliagorman** [dattalab/keypoint-moseq#27]
When I run the generate trajectory plots command, I get this keyword error but I don't see anywhere I can change the keyword from fps to 'duration' in my code when I command+f 'fps'

<img width="682" alt="Screenshot 2023-04-27 at 2 08 35 PM" src="https://user-images.githubusercontent.com/32439305/234991393-1c14b09f-5cfb-4e2a-af7a-a73a87e58498.png">

**Comment by calebweinreb** [comment]
This will be fixed in the next release. In the meantime, you can avoid the error by adding "save_gifs=False" when making trajectory plots. If you want trajectory plot videos, you can also include "save_mp4s=True".

**Comment by calebweinreb** [comment]
Fixed by https://github.com/dattalab/keypoint-moseq/commit/7656a1e67d9ec0502c517d105bcfcc02326f7e09

**Comment by juliagorman** [comment]
Do I need to remove the env and re-install for the newest release

**Comment by calebweinreb** [comment]
It's not released yet. For now you can do one of the following:

1. Install the dev version (in the same environment):
```
pip install -U git+https://github.com/dattalab/keypoint-moseq@dev
```
2. Avoid saving gifs (https://github.com/dattalab/keypoint-moseq/issues/27#issuecomment-1527230864)
3. Downgrade imageio, e.g.
```
pip install --force-reinstall imageio==2.23.0
```
