### ISSUE TITLE
ValueError: cannot convert float NaN to integer when generating crowd movies 

### ISSUE THREAD

**Issue by juliagorman** [dattalab/keypoint-moseq#28]
Able to generate grid movies but not crowd movies.

<img width="897" alt="Screenshot 2023-04-28 at 12 08 51 PM" src="https://user-images.githubusercontent.com/32439305/235232765-ecfdc706-4f18-45f1-aa45-be8ef223aa04.png">

**Comment by calebweinreb** [comment]
This is addressed by https://github.com/dattalab/keypoint-moseq/commit/bcc06f1c797301854918f20e2fc99b7c45abaefc and will be fixed in the next release!

**Comment by juliagorman** [comment]
I just updated kp moseq and I am still getting this error

**Comment by calebweinreb** [comment]
Can you make sure the code was successfully updated? Try
```
import keyoint_moseq
print(keyoint_moseq.__version__)
```
If you get an error then it wasn't updated. To update, make sure you run `pip instal -U keypoint-moseq` while in the correct conda environment, and also make sure to restart the notebook kernel.
