### ISSUE TITLE
Feature request: make positional rotation optional or choose direction of rotation?

### ISSUE THREAD

**Issue by stowerslab** [dattalab/keypoint-moseq#31]
We have videos of headfixed mice that are being flipped upside down during the error calibration and PCA extraction (probably because of rotational alignment) so we are wondering if that can be made optional or if the direction of alignment can be changed

![image](https://user-images.githubusercontent.com/36417259/235390425-e60a8582-8344-4dee-9150-1f5201f7be25.png)

**Comment by calebweinreb** [comment]
I think the fact that the video is flipped upside down here is just a quirk of ipywidgets. Thanks for pointing this out! 

But you do raise a more substantive point, which is that the heading-angle component of the modeling framework may not be appropriate for head-fixed setups. There is actually a setting in the config called "fix_heading" that addresses this. In your case you could try setting "fix_heading=True". This is still an experimental feature and in general we haven't applied keypoint-MoSeq to headfixed data before. It might be worth trying both options (fix_heading=True/False) and seeing which one produces more reasonable syllables.

**Comment by stowerslab** [comment]
hey caleb :) tried both True/False for the heading and it didnt change the orientation (still upside down)

**Comment by calebweinreb** [comment]
The `fix_heading` parameter isn't related to the frames being upside down during calibration. 

- The calibration upside-down thing is just a fluke of holoviews. It won't affect the results (as long as you can still recognize the correct location for each keypoint)
-  The `fix_heading` parameter determines whether points are rotationally aligned during model fitting.

**Comment by stowerslab** [comment]
gotcha!
