### ISSUE TITLE
Generate Trajectories:  The keyword `fps` is no longer supported. Use `duration`(in ms) instead, e.g. `fps=50` == `duration=20` (1000 * 1/50).

### ISSUE THREAD

**Issue by samarth-wustl** [dattalab/keypoint-moseq#33]
![image](https://user-images.githubusercontent.com/110621754/235543720-a82d4172-2be6-4686-a57e-bb36093ad918.png)

**Comment by samarth-wustl** [comment]
This is for moseq 0.0.5

**Comment by calebweinreb** [comment]
This shouldn't be the case for 0.0.5. Can you confirm that that's the current version you have installed? In the following traceback (which you sent over slack), the problematic line reflects the code as of 0.0.3 at the latest. 

![image](https://user-images.githubusercontent.com/6147762/235549526-43c7eaec-792a-423e-bf62-a8732b7ce305.png)

**Comment by calebweinreb** [comment]
In any case, even without the latest release this problem can be addressed by not saving a gif of the trajectory plots (`save_gifs=False`). If you still want an animation, you can save an mp4 instead (`save_mp4s=True`). To the command would be:
```
kpms.generate_trajectory_plots(coordinates=coordinates, name=name, project_dir=project_dir, 
                               save_figs=False, save_mp4s=True, **config())
```
