### ISSUE TITLE
`find_matching_videos` is too permissive

### ISSUE THREAD

**Issue by timsainb** [dattalab/keypoint-moseq#4]
If you have two videos, 1.avi and 10.avi, the find_matching_videos will think both 1.avi and 10.avi will match 10.csv, 

For example, my videos are in the format `{camera}.{datetime}.{framenumber}.avi` (`Top.22181547.486027.avi`), which causes the same error. 

This is because of 
`os.path.basename(key).startswith(video)`

Error: 
```
AssertionError: More than one video matches Top.22181547.4860270DLC_dlcrnetms5_23_03_2
1_DLC_enhancedMar21shuffle1_200000.h5
(['/n/groups/datta/tim_sainburg/projects/23-02-24-chronic-
pipeline/models/dlc/23_03_21_DLC_enhanced-
tim-2023-03-21/videos/Top.22181547.486027.avi',
'/n/groups/datta/tim_sainburg/projects/23-02-24-chronic-
pipeline/models/dlc/23_03_21_DLC_enhanced-
tim-2023-03-21/videos/Top.22181547.4860270.avi'])
```

one fix would be to select the longest match. 

e.g. 

```
if len(matches) > 0:
  longest_match = np.argmax([len(i) for i in matches])
  matches = [matches[longest_match]]
```

or, if you somehow knew the DLC model name (here DLC_dlcrnetms5_23_03_2) you could look for a specific match rather than startswith

**Comment by calebweinreb** [comment]
fixed in https://github.com/dattalab/keypoint-moseq/commit/d93eb0504acaad6f65817537c15ac6a66ac84040
