### ISSUE TITLE
kernel dies while running PCA

### ISSUE THREAD

**Issue by vickerse1** [dattalab/keypoint-moseq#41]
Hi,

With the Windows GPU version installed, all of the suggested jupyter lab code runs fine until the PCA cell, and then the kernel dies and there is no further error message. 

When I run "python -c "import jax; print(jax.devices())"", I get:

[StreamExecutorGpuDevice(id=0, process_index=0)]

Does this mean the GPU is not being used?

Thanks,

Evan

**Comment by calebweinreb** [comment]
It seems like the GPU is being used. Have you followed any of the steps in [troubleshooting guide](file:///Users/calebweinreb/Dropbox%20(HMS)/caleb%20weinreb/PROJECTS/MOUSE_SURVEILANCE/22_3_1_keypoint_MOSEQ/official_pipelines/keypoint-moseq/docs/build/html/FAQs.html#dead-kernel)? My guess is that some other process is hogging the GPU memory. To check, you can shut down the current notebook kernel and check what percent of the GPU VRAM is being available. It should be close to 100%. If it's not then maybe shutdown all the other notebook kernels and check again?

**Comment by vickerse1** [comment]
My GPU Load looks low, and no other problems are detected. I will retry under low CPU load conditions later (running CPU version now, want to let it finish), but I doubt that's an issue.

Found a similar issue here where problem was code bug, no idea if it might apply here though:

https://github.com/catboost/catboost/issues/1735
