### ISSUE TITLE
How to choose state number ？

### ISSUE THREAD

**Issue by KelvinTao** [dattalab/keypoint-moseq#46]
Hi, I want to know how to choose the state number. Is it automatically calculated by model ? Is there a suitable method to get a suitable state number ?

**Comment by calebweinreb** [comment]
Yes, the state number is automatically determined by the model using a hierarchical Dirichlet process prior. It reflects the inherent diversity of behaviors present as well as the size of the dataset. The following sections of the FAQ in the keypoint-moseq docs may be helpful:

https://keypoint-moseq.readthedocs.io/en/latest/FAQs.html#how-much-data-do-i-need
https://keypoint-moseq.readthedocs.io/en/latest/FAQs.html#interpreting-model-outputs
