### ISSUE TITLE
changing frame rate

### ISSUE THREAD

**Issue by lencriv** [dattalab/keypoint-moseq#47]
I was wondering if it is possible to change the frame rate of the acquired data or change the optimal syllable duration. I am acquiring at 60fps but it looks like the duration was optimized for 30fps.

**Comment by calebweinreb** [comment]
In general all users will have to adjust `kappa` when fitting a model, even if they acquire at 30Hz. So you could maybe aim for a median duration of ~24 frames. The following parts of the FAQs in the docs might be useful:

https://keypoint-moseq.readthedocs.io/en/latest/FAQs.html#choosing-the-target-syllable-duration
https://keypoint-moseq.readthedocs.io/en/latest/FAQs.html#number-of-model-fitting-iterations
