### ISSUE TITLE
ValueError: too many values to unpack (expected 2) When loading data

### ISSUE THREAD

**Issue by juliagorman** [dattalab/keypoint-moseq#49]
I got this error when loading the data. The path is correct since the config file went to the right place. I have also updated my version of keypoint moseq to v 0.1.2 
<img width="956" alt="Screenshot 2023-05-18 at 6 26 04 PM" src="https://github.com/dattalab/keypoint-moseq/assets/32439305/3f08a367-3d3f-40cf-ac7d-a5cc5ef74a4f">

**Comment by calebweinreb** [comment]
As of 0.1.2 that line has to be changed to
```
coordinates, confidences, bodyparts = kpms.load_deeplabcut_results(dlc_results)
```
