### ISSUE TITLE
Unable to install using conda on Windows -- UnsatisfiableError

### ISSUE THREAD

**Issue by ryanschwark** [dattalab/keypoint-moseq#57]
**For reference, our PC has a GPU and the following specs: 

- Windows 11 Pro OS build 22000.1936
- 2th Gen Intel(R) Core(TM) i7-12700K, 3.60 GHz
- 64.0 GB installed RAM

After trying to install Keypoint-MoSeq using the conda instructions, we encountered an error in which there were multiple conflicts, preventing installation. Using the Anaconda shell, we entered the following commands and received the following errors:**

(base) C:\Users\Abdus-saboor>git clone https://github.com/dattalab/keypoint-moseq
Cloning into 'keypoint-moseq'...
remote: Enumerating objects: 1488, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (34/34), done.
Receiving objects: 100% (1488/1488), 10.01 MiB | 46.18 MiB/s, done.31

Resolving deltas: 100% (1037/1037), done.

(base) C:\Users\Abdus-saboor>cd keypoint-moseq

(base) C:\Users\Abdus-saboor\keypoint-moseq>conda env create -f conda_envs\environment.win64_gpu.yml
Collecting package metadata (repodata.json): done
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for python cudnn cudatoolkit pip:  25%|███████▊                       | 2/8 [00:00<00:00, 18.44it/s]\failed
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for cudnn cudatoolkit:  38%|███████████████▊                          | 3/8 [00:00<00:00,  7.69it/s]|failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
pip -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|>=3.7|>=3.6|>=3|3.4.*']
pip -> setuptools -> python[version='!=3.0,!=3.1,!=3.2,!=3.3,!=3.4|>=3.8|2.7.*|>=3.6|2.7|>=3.6|>=2.7|>=3.7,<4.0|>=3.6,<4.0']

Package ucrt conflicts for:
python=3.9 -> openssl[version='>=1.1.1t,<1.1.2a'] -> ucrt[version='>=10.0.20348.0']
cudnn=8.2 -> cudatoolkit[version='>=11.0,<11.4'] -> ucrt[version='>=10.0.20348.0']
cudatoolkit=11.1 -> ucrt[version='>=10.0.20348.0']
pip -> python[version='>=3.11,<3.12.0a0'] -> ucrt[version='>=10.0.20348.0']

Package cudatoolkit conflicts for:
cudatoolkit=11.1
cudnn=8.2 -> cudatoolkit[version='10.2.*|>=11.0,<11.4|11.*']

Package vs2015_runtime conflicts for:
python=3.9 -> openssl[version='>=1.1.1t,<1.1.2a'] -> vs2015_runtime[version='>=14.15.26706|>=14.27.29016|>=14.29.30139|>=14.32.31332|>=14.34.31931|>=14.28.29325|>=14.29.30037']
python=3.9 -> vs2015_runtime[version='>=14.16.27012|>=14.16.27012,<15.0a0|>=14.16.27033']

Package vc conflicts for:
python=3.9 -> openssl[version='>=1.1.1t,<1.1.2a'] -> vc[version='9.*|>=14.2,<15|>=14,<15.0a0']
python=3.9 -> vc[version='>=14.1,<15|>=14.1,<15.0a0']
Note that strict channel priority may have removed packages required for satisfiability.

**Comment by calebweinreb** [comment]
To address this we:
- Uninstalled all versions of cuda besides 11.X (I think X=7?)
- Installed cudnn 8.2
