### ISSUE TITLE
AttributeError: module 'keypoint_moseq' has no attribute 'track_progress'

### ISSUE THREAD

**Issue by ryanschwark** [dattalab/keypoint-moseq#61]
Hi all,
While running the Keypoint MoSeq Analysis Visualization Notebook, in the Load Progress step, we enter this info into the cell:

import keypoint_moseq as kpms
model_dirname = '2023_06_05-12_29_0' # model directory name for the model to analyze
project_dir = 'model training notebook 6-5-2023' # project directory
progress_filename = 'progress.yaml' # progress file name
progress_paths = kpms.track_progress(model_dirname, project_dir, 'progress.yaml')

However, when we run this cell, we get the following error: 

AttributeError                            Traceback (most recent call last)
Cell In[6], line 7
      4 project_dir = 'model training notebook 6-5-2023' # project directory
      5 progress_filename = 'progress.yaml' # progress file name
----> 7 progress_paths = kpms.track_progress(model_dirname, project_dir, 'progress.yaml')

AttributeError: module 'keypoint_moseq' has no attribute 'track_progress'

Any idea what might be causing it? Did I enter the project directory/model directory name in the incorrect format? Thanks!

**Comment by calebweinreb** [comment]
Make sure you're using the most recent version of the notebook. We've been updating it recently:

https://github.com/dattalab/keypoint-moseq/blob/sherry_updates/docs/source/analysis.ipynb

**Comment by ryanschwark** [comment]
Thank you!! The newly updated version of the notebook worked. That's my bad for not having the most up-to-date version!
