### ISSUE TITLE
AttributeError: module 'keypoint_moseq' has no attribute 'load_keypoints'

### ISSUE THREAD

**Issue by ryanschwark** [dattalab/keypoint-moseq#63]
Hi all,

When using the most up-to-date version of the tutorial notebook for model training (https://github.com/dattalab/keypoint-moseq/blob/main/docs/source/tutorial.ipynb), we've run into an error during the Load Data step. Any idea what be causing this issue? We run the following cell and receive the resulting error:

#load data (e.g. from DeepLabCut)
keypoint_data_path = 'Identity tracking test\Identity tracked keypoint videos' # can be a file, a directory, or a list of files
coordinates, confidences, bodyparts = kpms.load_keypoints(keypoint_data_path, 'sleap')
#format data for modeling
data, labels = kpms.format_data(coordinates, confidences=confidences, **config())

AttributeError                            Traceback (most recent call last)
Cell In[21], line 3
      1 # load data (e.g. from DeepLabCut)
      2 keypoint_data_path = 'Identity tracking test\Identity tracked keypoint videos' # can be a file, a directory, or a list of files
----> 3 coordinates, confidences, bodyparts = kpms.io.load_sleap_results(keypoint_data_path)
      5 # format data for modeling
      6 data, labels = kpms.format_data(coordinates, confidences=confidences, **config())

AttributeError: module 'io' has no attribute 'load_sleap_results'

**Comment by calebweinreb** [comment]
Try `kpms.load_sleap_results`?
