### ISSUE TITLE
Issue with DLC video data

### ISSUE THREAD

**Issue by kjmartin44** [dattalab/keypoint-moseq#73]
I am attempting to use the calibration step with my deeplabcut imported data but it seems to be having difficulty identifying my video and csv matches.  I found that adding the suffix that DLC adds to your data during testing to the video names allowed it to pair some of them, but it worked inconsistently.  Is there a way to fix this problem?  I attempted the solution from the closed section of the issues section that had a similar issue here and it did not work for me.

**Comment by calebweinreb** [comment]
Can you send:
- info on the names of the videos and how they are organized into directories
- the same thing for the deeplabcut files
- the output of `coordinates.keys()`
- how you set `video_dir` in your config
- examples of videos that were successfully matched and not successfully matched?

**Comment by kjmartin44** [comment]
I seem to have had an error in my config.  My directory was to the wrong folder which only had half of the videos and csvs in it. The code now works. Thank you.
