### ISSUE TITLE
BLAS Support Error in kpms.fit_pca

### ISSUE THREAD

**Issue by lukeafBU** [dattalab/keypoint-moseq#78]
Hello,

I am operating on Windows 10, cudnn Version 8.2.1 on Build cuda11.3_0. I locally installed keypoint moseq via conda, and am only using the example DLC data provided.

I have run into a persistent error that I cannot work around. I can successfully execute all operations through `kpms.noise_calibration(project_dir, coordinates, confidences, **config())`. 

However, when I attempt to execute the pca fit as follows:
`pca = kpms.fit_pca(**data, **config())`
I am met with this error (see attacehd screenshot for full details): XlaRuntimeError: INTERNAL: Attempting to perform BLAS operation using StreamExecutor without BLAS support

My GPU usage when executing this command is low (<5%). Also, I am unsure if this is relevant but wanted to mention it in the event that it impacted my situation: I am encountering the same/similar issue that poster in issue#29 lists, whereby they have trouble executing the code when launching jupyter notebook from the same keypoint_moseq environment. For that reason, I too have only found success when I launch a separate instance of jupyter notebook manually (after registering the keypoint moseq kernal). 

Has anyone else encountered this BLAS error or have suggestions about how to resolve this? 

Thank you!

Best,
Luke

![BLAS_error](https://github.com/dattalab/keypoint-moseq/assets/89997218/fc6a3888-3af8-4539-877f-f70b3723c6fd)

**Comment by calebweinreb** [comment]
Can you try the pip installation? That might make it easier to debug since conda installs its own private versions of cuda and cudnn. (Also make sure you either delete the existing keypoint_moseq env or do the pip install in a differently-named env).

Also, have you confirmed your cudnn installation? E.g. used it in another package? Another way would be to run the following 
```
type "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\include\cudnn.h" | findstr "CUDNN_MAJOR CUDNN_MINOR CUDNN_PATCHLEVEL"
```

**Comment by calebweinreb** [comment]
Closing this since it's stale.
