### ISSUE TITLE
Docs links

### ISSUE THREAD

**Issue by talmo** [dattalab/keypoint-moseq#8]
It'd be helpful to have some more links to the docs on the GitHub repo.

Right now the docs sit at: https://dattalab.github.io/moseq2-website/readthedocs/keypoint-moseq

Not the easiest URL to remember, though I'm assuming you're planning on eventually hosting it on ReadTheDocs?

In any case, this URL could be added to the website field in the GitHub repository settings so it shows up on the top-right of the repo. A nice prominent link in the README wouldn't be bad either!

**Comment by calebweinreb** [comment]
Fixed in https://github.com/dattalab/keypoint-moseq/commit/5ab41a795af56056e987b3f20a496497392459ec
