### ISSUE TITLE
Updating to keypoint_moseq 2.0

### ISSUE THREAD

**Issue by ellaksay** [dattalab/keypoint-moseq#80]
Hello! I am updated to keypoint_moseq 2.0 by using `pip install -U keypoint_moseq` with the conda environment activated in the terminal and relaunching the jupyter lab. However, when I check using kpms.__version__ it says it's still running on keypoint_moseq version 1.5. Could this be due to jupyter lab and kpms being managed by different things? If so, what would be the best fix such that updating kpms would translate to the jupyter lab notebook. I have also tried running `!pip install -U keypoint_moseq` directly in jupyter lab and still no change. Thank you!

**Comment by calebweinreb** [comment]
In jupyter lab what kernel is being used? It should say in the top right.

**Comment by calebweinreb** [comment]
OK well for now you can just `pip install ipython_genutils` and that should work. We'll also release a new version with that dependency added
