### ISSUE TITLE
Installation Error via Mamba on a Linux HPC running Ubuntu20.04 on a node with an RTX 3070 GPU

### ISSUE THREAD

**Issue by jkbhagatio** [dattalab/keypoint-moseq#84]
When trying to mamba install from the 'environment.linux_gpu.yml' file, got the following error:

![image](https://github.com/dattalab/keypoint-moseq/assets/14895866/2b91739d-67e4-487d-ba0e-8675bd262684)

Though `nvcc --version` on this node returns: 

![image](https://github.com/dattalab/keypoint-moseq/assets/14895866/589410be-4f59-4232-a923-e45993344484)

Any suggestions?

**Comment by calebweinreb** [comment]
Thanks for opening this issue! We've noticed some errors for the Windows conda installation option too recently - so its possible that something has changed in the chain of dependencies.

For now you could try installing via pip? (tote that this means you need to install cudNN manually). I will also look into the the conda configs and get back to you soon.

**Comment by jkbhagatio** [comment]
Oops sorry! Two things fixed this:

- I had some default packages being installed from my '~/.condarc' that I commented out.
- I specifiied 'conda-nvcc<12.0' in the .yml.
