### ISSUE TITLE
installing jupyter nbextensions

### ISSUE THREAD

**Issue by ligeralde** [dattalab/keypoint-moseq#94]
Using mamba on Apple M2 Max hardware, i did the following steps as per the keypoint-moseq docs:

```
git clone https://github.com/dattalab/keypoint-moseq
cd keypoint-moseq 
conda env create -f conda_envs/environment.mac_cpu.yml
conda activate keypoint_moseq
python -m ipykernel install --user --name=keypoint_moseq
```

But then, when i run 
`jupyter nbextension install --py jupyter_nbextensions_configurator --sys-prefix`

I get the following error:

```
Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

optional arguments:
usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir] [--paths] [--json] [--debug] [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

optional arguments:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands: console dejavu events execute kernel kernelspec lab labextension labhub migrate nbconvert notebook run server troubleshoot trust

Jupyter command `jupyter-nbextension` not found.
```
is it under labextension instead?

**Comment by calebweinreb** [comment]
Sorry for the late response to this. Did you end up finding a solution? I don't have much experience using mamba so I'm not sure the best way forward. I will note, however, that the jupyter extensions are only needed for the analysis notebook (so you can still fit a keypoint-moseq model with the installation you already have) and were are planning to release a new version of the analysis notebook soon that doesn't need these extensions anyway.

**Comment by calebweinreb** [comment]
Closing since we no longer require jupyter extensions as of version 0.3.1
