### ISSUE TITLE
GPU not being utilized during model training

### ISSUE THREAD

**Issue by ryanschwark** [dattalab/keypoint-moseq#99]
Hi all,

Recently we've discovered that our PC is likely not utilizing our GPU when model training, causing the kernel to die when model training (see attached file). 
![GPU not being utilized](https://github.com/dattalab/keypoint-moseq/assets/124389408/2951e2c0-80ca-49f2-b48e-2eddfb7ae1c6)

I was wondering, what might be causing the GPU to not be utilized? My PC specs are: Windows 11 Pro OS build 22000.1936, with a 12th Gen Intel(R) Core(TM) i7-12700K, 3.60 GHz, and 64.0 GB installed RAM. I installed keypoint-MoSeq using pip, and have also downloaded the appropriate CUDA 11.1 / cuDNN 8.2.

What might be causing the issue? Thanks so much!

**Comment by calebweinreb** [comment]
What makes you say its not being utilized? It looks like 98% of the memory is being used.

**Comment by ryanschwark** [comment]
Hi,

Ahhh OK I see, that's my bad. You're right, looks like it is using 98% of the GPU!

Thanks!
